<a href="https://colab.research.google.com/github/ChanukaDasun/Next-Word-Prediction-LSTM/blob/main/next_word_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import tensorflow as tf

In [4]:
with open('/content/python.txt', 'r', encoding='utf-8') as file:
    python_text = file.read()

In [5]:
python_text

'Python is a high-level, general-purpose programming language. Its design philosophy emphasizes code readability with the use of significant indentation.[34] Python is dynamically type-checked and garbage-collected. It supports multiple programming paradigms, including structured (particularly procedural), object-oriented and functional programming.\n\nGuido van Rossum began working on Python in the late 1980s as a successor to the ABC programming language. Python 3.0, released in 2008, was a major revision and not completely backward-compatible with earlier versions. Beginning with Python 3.5, capabilities and keywords for typing were added to language, allowing optional static typing.[36] Currently only versions in the 3.x series are supported.\n\nPython has gained widespread use in the machine learning community. It is widely taught as an introductory programming language. Since 2003, Python has consistently ranked in the top ten of the most popular programming languages in the TIOB

In [6]:
tokenizer = tf.keras.preprocessing.text.Tokenizer()

In [7]:
# tokenized extracted text using tokenizer
tokenizer.fit_on_texts([python_text])

In [8]:
tokenizer.get_config()

{'num_words': None,
 'filters': '!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
 'lower': True,
 'split': ' ',
 'char_level': False,
 'oov_token': None,
 'document_count': 1,
 'word_counts': '{"python": 28, "is": 9, "a": 13, "high": 1, "level": 1, "general": 1, "purpose": 1, "programming": 14, "language": 7, "its": 1, "design": 2, "philosophy": 1, "emphasizes": 1, "code": 2, "readability": 1, "with": 7, "the": 24, "use": 2, "of": 11, "significant": 1, "indentation": 1, "34": 1, "dynamically": 1, "type": 1, "checked": 1, "and": 19, "garbage": 2, "collected": 1, "it": 6, "supports": 1, "multiple": 1, "paradigms": 2, "including": 3, "structured": 2, "particularly": 1, "procedural": 1, "object": 2, "oriented": 3, "functional": 2, "guido": 2, "van": 4, "rossum": 4, "began": 2, "working": 1, "on": 5, "in": 16, "late": 2, "1980s": 2, "as": 9, "successor": 2, "to": 13, "abc": 2, "3": 14, "0": 6, "released": 6, "2008": 2, "was": 10, "major": 2, "revision": 2, "not": 3, "completely": 2, "backward": 3, "

In [9]:
tokenizer.word_index

{'python': 1,
 'the': 2,
 'and': 3,
 'in': 4,
 'programming': 5,
 '3': 6,
 'a': 7,
 'to': 8,
 'of': 9,
 'was': 10,
 'is': 11,
 'as': 12,
 'language': 13,
 'with': 14,
 '2': 15,
 'it': 16,
 '0': 17,
 'released': 18,
 'on': 19,
 'versions': 20,
 'by': 21,
 'support': 22,
 'van': 23,
 'rossum': 24,
 'for': 25,
 'are': 26,
 'supported': 27,
 '9': 28,
 'security': 29,
 '7': 30,
 'including': 31,
 'oriented': 32,
 'not': 33,
 'backward': 34,
 'x': 35,
 'series': 36,
 'has': 37,
 'community': 38,
 'since': 39,
 'many': 40,
 'new': 41,
 'design': 42,
 'code': 43,
 'use': 44,
 'garbage': 45,
 'paradigms': 46,
 'structured': 47,
 'object': 48,
 'functional': 49,
 'guido': 50,
 'began': 51,
 'late': 52,
 '1980s': 53,
 'successor': 54,
 'abc': 55,
 '2008': 56,
 'major': 57,
 'revision': 58,
 'completely': 59,
 'compatible': 60,
 'earlier': 61,
 'typing': 62,
 'added': 63,
 'languages': 64,
 'which': 65,
 '24': 66,
 'at': 67,
 'designed': 68,
 '13': 69,
 'implementation': 70,
 'december': 71,
 'pro

In [10]:
input_sentences = []
for sentence in python_text.split('\n'):
  print(sentence)
  token_list = tokenizer.texts_to_sequences([sentence])[0]
  print(token_list)
  for i in range(1, len(token_list)):
    sequence = token_list[:i+1]
    input_sentences.append(sequence)

Python is a high-level, general-purpose programming language. Its design philosophy emphasizes code readability with the use of significant indentation.[34] Python is dynamically type-checked and garbage-collected. It supports multiple programming paradigms, including structured (particularly procedural), object-oriented and functional programming.
[1, 11, 7, 95, 96, 97, 98, 5, 13, 99, 42, 100, 101, 43, 102, 14, 2, 44, 9, 103, 104, 105, 1, 11, 106, 107, 108, 3, 45, 109, 16, 110, 111, 5, 46, 31, 47, 112, 113, 48, 32, 3, 49, 5]

[]
Guido van Rossum began working on Python in the late 1980s as a successor to the ABC programming language. Python 3.0, released in 2008, was a major revision and not completely backward-compatible with earlier versions. Beginning with Python 3.5, capabilities and keywords for typing were added to language, allowing optional static typing.[36] Currently only versions in the 3.x series are supported.
[50, 23, 24, 51, 114, 19, 1, 4, 2, 52, 53, 12, 7, 54, 8, 2, 55

In [11]:
input_sentences[:5] # see there not in the same length so we want to add paddings to each

[[1, 11],
 [1, 11, 7],
 [1, 11, 7, 95],
 [1, 11, 7, 95, 96],
 [1, 11, 7, 95, 96, 97]]

In [13]:
max_length = max([len(input_sentence) for input_sentence in input_sentences])
max_length

150

In [14]:
input_sentences = np.array(tf.keras.preprocessing.sequence.pad_sequences(input_sentences, maxlen=max_length, padding='pre'))

In [25]:
input_sentences[0] # here last -> label , and rest are -> features

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1, 11],
      dtype=int32)

In [23]:
X = input_sentences[:, :-1] # features
y = input_sentences[:, -1] # label

In [24]:
X[0], y[0]

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int32),
 np.int32(11))

In [27]:
no_of_classes = len(tokenizer.word_index) + 1 # here no of classes means by -> how many numbers that we have in this particular dataset
no_of_classes

314

In [28]:
# make our labels in order to no_of_classes (onehot encoding)
y = np.array(tf.keras.utils.to_categorical(y, num_classes=no_of_classes))

In [29]:
y[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [30]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Embedding(no_of_classes, 80, input_length=max_length-1))
model.add(tf.keras.layers.LSTM(100))
model.add(tf.keras.layers.Dense(no_of_classes, activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [38]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 149, 80)        │        25,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 100)            │        72,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 314)            │        31,714 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 387,704 (1.48 MB)

 Trainable params: 129,234 (504.82 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 258,470 (1009.65 KB)

In [32]:
model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [33]:
history = model.fit(X, y, epochs=100)

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 4s 101ms/step - accuracy: 0.0123 - loss: 5.7455
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 4s 153ms/step - accuracy: 0.0419 - loss: 5.4915
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 4s 103ms/step - accuracy: 0.0317 - loss: 5.2612
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 104ms/step - accuracy: 0.0613 - loss: 5.2459
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 101ms/step - accuracy: 0.0306 - loss: 5.2994
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 4s 168ms/step - accuracy: 0.0386 - loss: 5.1845
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 4s 101ms/step - accuracy: 0.0510 - loss: 5.2187
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 101ms/step - accuracy: 0.0389 - loss: 5.1519
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 101ms/step - accuracy: 0.0544 - loss: 5.1165
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - accuracy: 0.0513 - loss: 5.0541
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 161ms/step - accuracy: 0.0579 - loss: 4.9360
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 4

In [39]:
input_text = "Python is"
token_list = tokenizer.texts_to_sequences([input_text])[0]
print(token_list)

[1, 11]


In [40]:
token_list = tf.keras.preprocessing.sequence.pad_sequences([token_list], maxlen=max_length-1, padding='pre')
token_list

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  1, 11]], dtype=int32)

In [41]:
preds = np.argmax(model.predict(token_list), axis=-1)
preds

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 212ms/step


array([7])

In [42]:
for word, index in tokenizer.word_index.items():
  if index == preds:
    print(word)

a


In [63]:
def print_pred_word(input: str, no_of_words_to_pred: int):
  for i in range(no_of_words_to_pred):
    token_list = tokenizer.texts_to_sequences([input])[0]
    token_list = tf.keras.preprocessing.sequence.pad_sequences([token_list], maxlen=max_length-1, padding='pre') # add padding
    preds = np.argmax(model.predict(token_list), axis=-1)
    output = ""
    for word, index in tokenizer.word_index.items():
      if index == preds:
        output = word
        break
    input += " " + output
  return input


In [65]:
print(print_pred_word("python is a high level general purpose programming language", 100))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━